PKG_NAME="usbredir"
PKG_VERSION="0.7"
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="LGPL-2.1"
PKG_SITE="http://spice-space.org/page/UsbRedir"
PKG_URL="http://spice-space.org/download/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain libusb"
PKG_PRIORITY="optional"
PKG_SECTION="devel"
PKG_SHORTDESC="A simple TCP daemon and set of libraries for the usbredir protocol (redirecting USB traffic)"
PKG_LONGDESC="A simple TCP daemon and set of libraries for the usbredir protocol (redirecting USB traffic)"
PKG_IS_ADDON="no"

PKG_AUTORECONF="no"
