PKG_NAME="virglrenderer"
PKG_VERSION="61846f92fe2d511d3a29438542f04c67d96fe2e9"
PKG_REV="1"
PKG_ARCH="x86_64"
PKG_LICENSE="GPL"
PKG_SITE="https://virgil3d.github.io/"
PKG_GIT_URL="https://anongit.freedesktop.org/git/virglrenderer.git"
PKG_DEPENDS_TARGET="toolchain libdrm libepoxy"
PKG_PRIORITY="optional"
PKG_SECTION="virtualization"
PKG_SHORTDESC="library used implement a virtual 3D GPU used by qemu"
PKG_LONGDESC="library used implement a virtual 3D GPU used by qemu"

PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"
