PKG_NAME="gnome-common"
PKG_VERSION="3.14.0"
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="GPL-3"
PKG_SITE="http://www.gtk.org/"
PKG_URL="https://git.gnome.org/browse/$PKG_NAME/snapshot/$PKG_NAME-$PKG_VERSION.tar.xz"
PKG_DEPENDS_HOST="toolchain"
PKG_PRIORITY="optional"
PKG_SECTION="tools"
PKG_SHORTDESC="Common files for development of Gnome packages"
PKG_LONGDESC="Common files for development of Gnome packages"
PKG_IS_ADDON="no"

PKG_AUTORECONF="yes"
