PKG_NAME="spice-protocol"
PKG_VERSION="0.12.11"
PKG_REV="1"
PKG_ARCH="x86_64"
PKG_LICENSE="GPL"
PKG_SITE="http://spice-space.org/"
PKG_URL="http://spice-space.org/download/releases/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain"
PKG_PRIORITY="optional"
PKG_SECTION="virtualization"
PKG_SHORTDESC="Headers defining the SPICE protocol"
PKG_LONGDESC="Headers defining the SPICE protocol"

PKG_IS_ADDON="no"
PKG_AUTORECONF="no"
