PKG_NAME="xcb-util-wm"
PKG_VERSION="0.4.1"
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="OSS"
PKG_SITE="http://xcb.freedesktop.org"
PKG_URL="http://xcb.freedesktop.org/dist/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain libxcb"
PKG_PRIORITY="optional"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="xcb-util-wm: The xcb-util-wm package contains libraries which provide client and window-manager helpers for EWMH and ICCCM."
PKG_LONGDESC="The xcb-util-wm package contains libraries which provide client and window-manager helpers for EWMH and ICCCM."

PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"
