PKG_NAME="xcb-util-cursor"
PKG_VERSION="0.1.2"
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="OSS"
PKG_SITE="http://xcb.freedesktop.org"
PKG_URL="http://xcb.freedesktop.org/dist/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_TARGET="toolchain libxcb xcb-util-renderutil xcb-util-image"
PKG_PRIORITY="optional"
PKG_SECTION="x11/lib"
PKG_SHORTDESC="xcb-util-wm: The xcb-util-cursor package provides a module that implements the XCB cursor library. It is a the XCB replacement for libXcursor."
PKG_LONGDESC="The xcb-util-cursor package provides a module that implements the XCB cursor library. It is a the XCB replacement for libXcursor."

PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"
